name: karunya_navigator
description: Karunya Navigator campus tour guide app.
version: 2.0.0+10
publish_to: 'none'

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  tourforge_baseline: any
  path_provider: ^2.0.13
  path: ^1.8.2
  url_launcher: ^6.1.12
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  open_filex: ^4.5.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_oss_licenses: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: false
  adaptive_icon_background: "#1D2D50"
  adaptive_icon_foreground: "assets/icon/icon.png"
  min_sdk_android: 24
